---
title: "03 Exploratory analysis"
author: "Alexandra Tejada-Strop"
format: html
execute:
  echo: true
  warning: false
  message: false
---

## Load Data
```{r}
library(tidyverse)
library(here)
library(skimr)

dir.create(here("results", "tables"), showWarnings = FALSE, recursive = TRUE)
dir.create(here("results", "figures"), showWarnings = FALSE, recursive = TRUE)

analytic_dat <- readRDS(here("data", "processed-data", "prams_analytic.rds"))

dim(analytic_dat)
```


## Screening distribution
```{r}
screen_tbl <- analytic_dat |> 
  count(screened) |> 
  mutate(pct = n/sum(n))

screen_tbl

saveRDS(
  screen_tbl,
  here("results", "tables", "screening_distribution.rds")
)
```

## Postpartum depression distribution

```{r}
analytic_dat |> 
  count(pp_depress_bin) |> 
  mutate(pct = n/sum(n))
```

## Cross-tabulation
```{r}
analytic_dat |>
  count(screened, pp_depress_bin) |>
  group_by(screened) |>
  mutate(pct = n/sum(n))
```

## Plot
```{r}
plot_screen_dep <- analytic_dat |>
  ggplot(aes(x = factor(screened),
             fill = factor(pp_depress_bin))) +
  geom_bar(position = "fill") +
  labs(
    x = "Prenatal Depression Screening",
    y = "Proportion",
    fill = "Postpartum Depressive Symptoms"
  )

plot_screen_dep

ggsave(
  filename = here("results", "figures", "screening_vs_postpartum_depression.png"),
  plot = plot_screen_dep,
  width = 7,
  height = 5
)
```

## Depression by Prior Depression During Pregnancy
```{r}
analytic_dat |>
  count(BPG_DEPRS8, pp_depress_bin) |>
  group_by(BPG_DEPRS8) |>
  mutate(pct = n/sum(n))
```

## Depression by Education
```{r}
analytic_dat |>
  count(MAT_ED, pp_depress_bin) |>
  group_by(MAT_ED) |>
  mutate(pct = n/sum(n))
```

## Proportion with Postpartum Depression and screening
```{r}
analytic_dat |>
  ggplot(aes(x = factor(screened),
             y = as.numeric(pp_depress_bin))) +
  stat_summary(fun = mean, geom = "bar") +
  labs(
    x = "Prenatal Depression Screening",
    y = "Proportion with Postpartum Depressive Symptoms"
  )
  ```