---
title: "04 Statistical analysis"
author: "Alexandra Tejada-Strop"
format: html
execute:
  echo: true
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(here)
library(tidymodels)
library(broom)

# Load analytic dataset
data_path <- here("data", "processed-data", "prams_analytic.rds")
stopifnot(file.exists(data_path))
dat <- readRDS(data_path)

# Make sure results folders exist
dir.create(here("results", "tables"), showWarnings = FALSE, recursive = TRUE)
dir.create(here("results", "output"), showWarnings = FALSE, recursive = TRUE)

# Quick check
glimpse(dat)
```

```{r}
# Outcome (binary)
# Assumes pp_depress_bin is coded 0/1 or FALSE/TRUE.

outcome <- "pp_depress_bin"

# Main exposure of interest
main_exposure <- "screened"


covariates <- c("BPG_DEPRS8", "MAT_ED")

all_vars <- c(outcome, main_exposure, covariates)
stopifnot(all(all_vars %in% names(dat)))

analysis_dat <- dat |>
  select(all_of(all_vars)) |>
  drop_na()

# Make outcome numeric 0/1 if needed
analysis_dat <- analysis_dat |>
  mutate(
    pp_depress_bin = as.numeric(pp_depress_bin),
    screened = as.factor(screened),
    BPG_DEPRS8 = as.factor(BPG_DEPRS8),
    MAT_ED = as.factor(MAT_ED)
  )

# Confirm
analysis_dat |> summarise(n = n())
```

```{r}
# Bivariate Model
fit_biv <- glm(
  pp_depress_bin ~ screened,
  data = analysis_dat,
  family = binomial()
)

biv_tbl <- broom::tidy(fit_biv, conf.int = TRUE, exponentiate = TRUE)

biv_tbl

saveRDS(biv_tbl, here("results", "tables", "glm_bivariate_screened.rds"))
saveRDS(fit_biv, here("results", "output", "glm_bivariate_screened.rds"))
```

```{r}
# Multivariate GLM
fit_multi <- glm(
  pp_depress_bin ~ screened + BPG_DEPRS8 + MAT_ED,
  data = analysis_dat,
  family = binomial()
)

multi_tbl <- broom::tidy(fit_multi, conf.int = TRUE, exponentiate = TRUE)

multi_tbl

saveRDS(multi_tbl, here("results", "tables", "glm_multivariable_main.rds"))
saveRDS(fit_multi, here("results", "output", "glm_multivariable_main.rds"))
```

```{r}
file.exists(here("results", "tables", "glm_bivariate_screened.rds"))
file.exists(here("results", "tables", "glm_multivariable_main.rds"))
file.exists(here("results", "output", "tidymodels_logistic_main.rds"))
```

```{r}
# Tidymodels expects a factor outcome for classification
analysis_dat2 <- analysis_dat |>
  mutate(pp_depress_bin = factor(pp_depress_bin, levels = c(0, 1)))

rec <- recipe(pp_depress_bin ~ screened + BPG_DEPRS8 + MAT_ED, data = analysis_dat2) |>
  step_dummy(all_nominal_predictors()) |>
  step_zv(all_predictors())

wf <- workflow() |>
  add_recipe(rec) |>
  add_model(logistic_reg() |> set_engine("glm"))

fit_wf <- fit(wf, data = analysis_dat2)

saveRDS(fit_wf, here("results", "output", "tidymodels_logistic_main.rds"))

fit_wf
```